export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  REVIEW_REASON_REQUIRED: "REVIEW_REASON_REQUIRED",
  STORAGE_UNAVAILABLE: "STORAGE_UNAVAILABLE"
} as const;
