/**
 * 错误码集中定义。service / controller 各自包装异常时引用，
 * 禁止只在一个全局位置吞掉全部异常。
 */
export const ERROR_CODES = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  REVIEW_REASON_REQUIRED: "REVIEW_REASON_REQUIRED",
  REVIEW_REVIEWER_REQUIRED: "REVIEW_REVIEWER_REQUIRED",
  REVIEW_NOTE_NOT_FOUND: "REVIEW_NOTE_NOT_FOUND",
  SECTION_NOT_FOUND: "SECTION_NOT_FOUND",
  DIFF_NOT_FOUND: "DIFF_NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
